[package]
name = "gotham_rest"
version = "0.1.0"
authors = ["Christoph Wurst <christoph@winzerhof-wurst.at>"]

[dependencies]
failure = "^0.1"
futures = "*"
gotham = "^0.2"
gotham_derive = "^0.2"
hyper = "*"
serde = "^1.0"
serde_derive = "^1.0"

[dev-dependencies]
mime = "*"
serde_json = "^1.0"
